[de APP_INFO
  ("name"      "picolisp-kv")
  ("version"   "0.14.1")
  ("summary"   "Redis-inspired in-memory key/value store written in PicoLisp")
  ("source"    "https://github.com/aw/picolisp-kv")
  ("author"    "Alexander Williams")
  ("license"   "MIT")
  ("copyright" "(c) 2020 Alexander Williams, On-Prem <license@on-premises.com>")
  ("requires"
    ("picolisp-unit"   "v3.0.0"      "https://github.com/aw/picolisp-unit.git") ]
