name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    strategy:
      matrix:
        arch: ['src64']
        version: ['pil21']

    steps:
      - uses: actions/checkout@v1
      - uses: aw/picolisp-action@v2
        with:
          version: ${{matrix.version}}
          architecture: ${{matrix.arch}}

      - name: Run the tests on PicoLisp ${{matrix.arch}} v${{matrix.version}}
        run: make check
